- type: ghostRole
  id: RedactedBorg
  name: ghost-role-information-redacted-borg
  description: ghost-role-information-redacted-borg-description
  rules: ghost-role-information-silicon-rules
  entityPrototype: PlayerBorgRedacted
  whitelisted: true
