- type: entity
  id: EngineeringTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: engineering techfab machine board
  description: A machine printed circuit board for a engineering techfab
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: EngineeringTechFab
      stackRequirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker

- type: entity
  id: ServiceTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: service techfab machine board
  description: A machine printed circuit board for a service techfab
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ServiceTechFab
      stackRequirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker

- type: entity
  id: ScienceTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: science techfab machine board
  description: A machine printed circuit board for a science techfab
  components:
    - type: Sprite
      state: science
    - type: MachineBoard
      prototype: ScienceTechFab
      stackRequirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker

- type: entity
  id: DeepFryerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: deep fryer machine board
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: KitchenDeepFryer
      stackRequirements:
        Capacitor: 1
        MatterBin: 1
        Steel: 4
        Glass: 2
        Cable: 5