- type: job
  id: Deputy
  name: job-name-deputy
  description: job-description-deputy
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # Frontier - 12 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 21600 # Frontier - 6 hrs
  startingGear: DeputyGear
  icon: "JobIconSecurityOfficer" # Frontier
  supervisors: job-supervisors-sergeant
  canBeAntag: false
  accessGroups: # Frontier
  - GeneralNfsdAccess # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: DeputyGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNfsd # Frontier
    back: ClothingBackpackNfsdBrownFilled # Frontier
    shoes: ClothingShoesBootsNfsdBrownFilled # Frontier
    eyes: ClothingEyesGlassesNfsd # Frontier
    head: ClothingHeadHatNfsdSmallCampaign # Frontier
    outerClothing: ClothingOuterArmorNfsd # Frontier
    id: DeputyPDA # Frontier
    ears: ClothingHeadsetNfsdBrown # Frontier
    belt: ClothingBeltNfsdWebbingFilled # Frontier
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
    gloves: ClothingHandsGlovesCombatNfsdBrown # Frontier
    neck: ClothingNeckNfsdBadgeSecurity # Frontier
  # innerClothingSkirt: ClothingUniformJumpskirtNfsd # Frontier
  # satchel: ClothingBackpackSatchelNfsdBrownFilled # Frontier
  # duffelbag: ClothingBackpackDuffelNfsdBrownFilled # Frontier
  # messenger: ClothingBackpackMessengerNfsdBrownFilled # Frontier
