- type: latheRecipePack
  id: NFServiceStatic
  recipes:
  - Durathread # Frontier
  - FoodCondimentSqueezeBottleClear # Frontier

- type: latheRecipePack
  id: NFService
  recipes:
  - ServiceSelectiveDropper # Frontier
  - PlantAnalyzer # Frontier
  - JanicartFlatpack # Frontier
  - PlantBagOfHolding # Delta-V

- type: latheRecipePack
  id: NFServiceBoardsStatic
  recipes:
  - CondimentDispenserCircuitboard

- type: latheRecipePack
  id: NFServiceBoards
  recipes:
  - KitchenAssemblerMachineCircuitboard # Frontier
  - ElectricRangeMachineCircuitboard # Frontier
  - ReagentGrinderMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard
  - BiogeneratorMachineCircuitboard
