# Base dungeon prototypes
- type: dungeonConfig
  id: Everything
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
    presets:
      - Bucket
      - Wow
      - SpaceShip
      - Tall

  - !type:CorridorDunGen
    width: 3
  
  - !type:DungeonEntranceDunGen
    count: 2

  - !type:RoomEntranceDunGen

  - !type:EntranceFlankDunGen

  - !type:ExternalWindowDunGen

  - !type:WallMountDunGen

  - !type:BoundaryWallDunGen

  - !type:JunctionDunGen
    width: 1

  - !type:JunctionDunGen

  - !type:AutoCablingDunGen

  - !type:CornerClutterDunGen

  data:
    entities:
      Cabling: CableApcExtension
      CornerWalls: WallReinforced
      Walls: WallSolid
    spawnGroups:
      CornerClutter: BaseClutter
      Entrance: BaseAirlock
      EntranceFlank: BaseWindow
      Junction: BaseAirlock
      WallMounts: BaseWallMounts
      Window: BaseWindow
    tiles:
      FallbackTile: FloorSteel
    whitelists:
      Rooms:
        tags:
        - CaveFactory
        - LavaBrig
        - LavaMercenary
        - SalvageExperiment
        - VirologyLab
        - SalvageOutpost

- type: entitySpawnEntry
  id: BaseClutter
  entries:
  - id: PottedPlantRandom
    amount: 1

- type: entitySpawnEntry
  id: BaseAirlock
  entries:
  - id: CableApcExtension
  - id: AirlockGlass

- type: entitySpawnEntry
  id: BaseWindow
  entries:
  - id: Grille
  - id: Window

- type: entitySpawnEntry
  id: BaseWallMounts
  entries:
    # Posters
    - id: RandomPosterLegit
      orGroup: content
    - id: ExtinguisherCabinetFilled
      prob: 0.2
      orGroup: content
    - id: RandomPainting
      prob: 0.05
      orGroup: content
    - id: DefibrillatorCabinetFilled
      prob: 0.1
      orGroup: content

# CaveFactory prototypes
- type: dungeonConfig
  id: CaveFactory
  data:
    colors:
      Decals: "#ffa64d96"
    spawnGroups:
      WallMounts: CaveFactoryWallMounts
    whitelists:
      Rooms:
        tags:
          - CaveFactory

  layers:
  - !type:PrototypeDunGen
    proto: Everything

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: entitySpawnEntry
  id: CaveFactoryWallMounts
  entries:
    # Posters
    - id: RandomPosterLegit
      orGroup: content
    - id: ExtinguisherCabinetFilled
      prob: 0.2
      orGroup: content
    - id: RandomPainting
      prob: 0.05
      orGroup: content

# MedSci prototypes
- type: dungeonConfig
  id: MedSci
  data:
    spawnGroups:
      WallMounts: MedSciWallMounts
    whitelists:
      Rooms:
        tags:
          - SalvageExperiment

  layers:
  - !type:PrototypeDunGen
    proto: Everything

- type: entitySpawnEntry
  id: MedSciWallMounts
  entries:
    - id: RandomPosterLegit
      orGroup: content
    - id: ExtinguisherCabinetFilled
      prob: 0.2
      orGroup: content
    - id: RandomPainting
      prob: 0.05
      orGroup: content
    - id: DefibrillatorCabinetFilled
      prob: 0.2
      orGroup: content

# FactoryDorms prototypes
- type: dungeonConfig
  id: FactoryDorms
  data:
    whitelists:
      Rooms:
        tags:
          - CaveFactory
  layers:
  - !type:PrototypeDunGen
    proto: Everything

# LavaMercenary prototypes
- type: dungeonConfig
  id: LavaMercenary
  data:
    colors:
      Decals: "#5E7C16"
    spawnGroups:
      Entrance: MercenaryAirlock
      WallMounts: LavaMercenaryWallMount
    whitelists:
      Rooms:
        tags:
          - LavaMercenary
  layers:
  - !type:PrototypeDunGen
    proto: Everything

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: entitySpawnEntry
  id: MercenaryAirlock
  entries:
    - id: CableApcExtension
    - id: AirlockMercenaryGlass

- type: entitySpawnEntry
  id: LavaMercenaryWallMount
  entries:
    # Posters
    - id: RandomPosterContraband
      orGroup: content
    - id: ExtinguisherCabinetFilled
      prob: 0.2
      orGroup: content
    - id: RandomPainting
      prob: 0.05
      orGroup: content

# VirologyLab prototypes
- type: dungeonConfig
  id: VirologyLab
  data:
    colors:
      Decals: "#467b41"
    spawnGroups:
      Entrance: VirologyAirlock
    whitelists:
      Rooms:
        tags:
          - VirologyLab

  layers:
  - !type:PrototypeDunGen
    proto: Everything

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: entitySpawnEntry
  id: VirologyAirlock
  entries:
    - CableApcExtension
    - AirlockVirologyGlass

# SalvageOutpost prototypes
- type: dungeonConfig
  id: SalvageOutpost
  data:
    colors:
      Decals: "#9A54BF"
    entities:
      CornerWalls: WallMining
      Walls: WallMining
    spawnGroups:
      Entrance: MiningAirlock
      EntranceFlank: MiningWindow
      Window: MiningWindow
    whitelists:
      Rooms:
        tags:
          - SalvageOutpost
  layers:
  - !type:PrototypeDunGen
    proto: Everything

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: entitySpawnEntry
  id: MiningAirlock
  entries:
    - CableApcExtension
    - AirlockMiningGlass

- type: entitySpawnEntry
  id: MiningWindow
  entries:
    - Grille
    - MiningWindow
