- type: entity
  id: ShredderMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: shredder machine board
  description: A machine printed circuit board for a shredder.
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: Shredder
      stackRequirements:
        MatterBin: 1
      materialRequirements:
        Glass: 1

- type: entity
  id: TilePrinterNFMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: tile-meister 5000 machine board
  description: A machine printed circuit board for an tile-meister 5000
  components:
    - type: MachineBoard
      prototype: TilePrinterNF
      stackRequirements:
        MatterBin: 2
        Manipulator: 2
      materialRequirements:
        Glass: 1

- type: entity
  id: SalvageTechFabCircuitboardNF
  parent: BaseMachineCircuitboard
  name: salvage techfab machine board
  description: A machine printed circuit board for a salvage techfab
  components:
    - type: Sprite
      state: supply
    - type: MachineBoard
      prototype: SalvageTechfabNF
      stackRequirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker

# TechFab
- type: entity
  id: NfsdTechFabCircuitboard
  parent: SecurityTechFabCircuitboard
  name: nfsd techfab machine board
  description: A machine printed circuit board for an nfsd techfab.
  components:
    - type: Sprite
      state: nfsd
    - type: MachineBoard
      prototype: NfsdTechFab

# Thrusters
- type: entity
  id: ThrusterSecurityMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: security thruster machine board
  components:
  - type: MachineBoard
    prototype: ThrusterSecurity
    stackRequirements:
      Capacitor: 3
    materialRequirements:
      Steel: 5

- type: entity
  id: ThrusterNfsdMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: nfsd thruster machine board
  components:
  - type: MachineBoard
    prototype: ThrusterNfsd
    stackRequirements:
      Capacitor: 3
    materialRequirements:
      Steel: 5

- type: entity
  id: SmallThrusterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: small thruster machine board
  components:
  - type: MachineBoard
    prototype: SmallThruster
    stackRequirements:
      Capacitor: 4
    materialRequirements:
      Steel: 5
  - type: StaticPrice
    price: 12.5

# Gyroscope
- type: entity
  id: GyroscopeSecurityMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: security gyroscope machine board
  components:
  - type: MachineBoard
    prototype: GyroscopeSecurity
    stackRequirements:
      Manipulator: 2
      Capacitor: 1
    materialRequirements:
      Glass: 2

- type: entity
  id: SmallGyroscopeSecurityMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: small security gyroscope machine board
  components:
  - type: MachineBoard
    prototype: SmallGyroscopeSecurity
    stackRequirements:
      Manipulator: 2
      Capacitor: 1
    materialRequirements:
      Glass: 2
  - type: StaticPrice
    price: 12.5

- type: entity
  id: GyroscopeNfsdMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: nfsd gyroscope machine board
  components:
  - type: MachineBoard
    prototype: GyroscopeNfsd
    stackRequirements:
      Manipulator: 2
      Capacitor: 1
    materialRequirements:
      Glass: 2

- type: entity
  id: SmallGyroscopeNfsdMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: small nfsd gyroscope machine board
  components:
  - type: MachineBoard
    prototype: SmallGyroscopeNfsd
    stackRequirements:
      Manipulator: 2
      Capacitor: 1
    materialRequirements:
      Glass: 2
  - type: StaticPrice
    price: 12.5

- type: entity
  id: SmallGyroscopeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: small gyroscope machine board
  components:
  - type: MachineBoard
    prototype: SmallGyroscope
    stackRequirements:
      Manipulator: 2
      Capacitor: 1
    materialRequirements:
      Glass: 2
  - type: StaticPrice
    price: 12.5
